### ISSUE TITLE
automatically revoke stale invitations

### ISSUE THREAD

**Issue by afeld** [18F/ghad#23]
- https://developer.github.com/v3/orgs/members/#list-pending-organization-invitations
- https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership

**Comment by JJediny** [comment]
Shouldn't be tracked as an issue until/unless its demonstrated to be one

**Comment by afeld** [comment]
[GitHub now automatically expires them.](https://github.blog/changelog/2020-02-05-self-expiring-repository-and-organization-invitations/)
