### ISSUE TITLE
GitHub user/team cleanup

### ISSUE THREAD

**Issue by afeld** [18F/ghad#26]
- [ ] Remove teams that are not associated with any repositories
- [ ] Remove members that are not part of any team

**Comment by its-a-lisa** [comment]
Linking here for when grooming the card in case it might be relevant. 

https://gsa-tts.slack.com/archives/CNW3GL70S/p1581520717145200

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/179

**Comment by afeld** [comment]
Want to move user management to be more centralized, so not going to worry about this for GitHub specifically.
