### ISSUE TITLE
Note when a repo is auto-archived

### ISSUE THREAD

**Issue by bengerman13** [18F/ghad#27]
As a developer on many infrequently-touched but actively-consumed projects, I would like to know when a repository is archived automatically.

This could be something like an email to the admins (this sounds hard to implement well) or an issue opened on the repo, or even just updating the repo description.

**Comment by mxplusb** [comment]
The fact 18F is autoarchiving our repositories signals, to me at least, that it's time to figure out how to move into our own organization where we control what happens.

**Comment by afeld** [comment]
This isn't something the Tech Portfolio is going to get to anytime soon, so closing to keep our board clean. Pull requests welcome!
