### ISSUE TITLE
try org-wide security settings

### ISSUE THREAD

**Issue by afeld** [18F/ghad#47]
## Background information

GitHub now has [organization-wide settings](https://github.com/organizations/18F/settings/security_analysis) to do things that ghad was built for:

<img width="776" alt="Screen Shot 2020-08-14 at 3 18 18 PM" src="https://user-images.githubusercontent.com/86842/90285264-8f801d80-de41-11ea-8ff8-97441ba44d0e.png">

If they work, we can probably deprecate [parts of] ghad.

## User stories

- As someone managing the TTS GitHub organizations, I want to ensure good security with as little effort or custom code as possible.

## Acceptance criteria

- Security alerts are enabled across all our repos across all [orgs we manage](https://handbook.tts.gsa.gov/github/#organizations)

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
