### ISSUE TITLE
Wallet me

### ISSUE THREAD

**Issue by SoheilAdmin** [18F/ghad#62]
## Implementation Steps

- [ ]

## Acceptance Criteria

- [bnb1f02mfm88mphj5d7ene0a9wrp8p8najxrcxlcz4 ]

**Comment by SoheilAdmin** [comment]
![Screenshot_۲۰۲۱-۱۲-۲۴-۲۰-۲۷-۲۶.png](https://user-images.githubusercontent.com/96382042/147372261-b0907810-976b-4372-a069-6526b903f441.png)
Wallet me 
[](bc1quc57lgsdhrxurmnp3hre07zfpx04jepdmcl65u  )

**Comment by geekygirlsarah** [comment]
Closing for spam and removing cryptocurrency address.
